name: CI/CD Breast Cancer API

on:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1️. Checkout del repo
      - uses: actions/checkout@v3

      # 2️. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️. Build de la imagen Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/breastcancer-api:v2 .

      # 4️. Correr contenedor para test
      - name: Run container
        run: docker run -d -p 5001:5001 --name test-container ${{ secrets.DOCKER_USERNAME }}/breastcancer-api:v2

      # 5️. Esperar un par de segundos para que arranque la API
      - name: Wait for API
        run: sleep 5

      # 6️. Test API con test_api.py
      - name: Test API
        run: python test_api.py

      # 7️. Detener y eliminar contenedor de test
      - name: Stop container
        run: docker stop test-container && docker rm test-container

      # 8️. Push a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/breastcancer-api:v2